### PR TITLE
Add a language switcher

### LINKED ISSUE #6: Add a framework for translations
Add support for other languages. I haven't looked into it yet, but I expect there's a framework or a standard way to do this for a single page React app, and we should use whatever tools we can that already exist and are common.

### PR DESCRIPTION
**Pull request by kas-catholic**
Adds a language switcher to change the locale. We'll wait to merge this
'til we have at least 2 well-supported languages.

Note that language names are intentionally untranslated - they should
always be in the native locale.

Fixes #6.

### CODE REVIEW

**Comment by JohnRDOrazio** [comment]
I have started integration of the language files with my weblate instance:
https://translate.johnromanodorazio.com/engage/confessit-web/

You can add a widget to the repo README if you like, which can show the current state of translations:
https://translate.johnromanodorazio.com/widgets/confessit-web/

In order for the weblate instance to pick up automatically any changes to the English language source file, you can add a web hook to the repository:
https://docs.weblate.org/en/weblate-4.9.1/admin/continuous.html#github-setup

Specifically: `repository settings` -> `webhooks` -> 'Add webhook` 
Under `payload url` put `https://translate.johnromanodorazio.com/hooks/github/`.
For `content type` choose `application/x-www-form-urlencoded`.
For `which events will trigger this hook` choose `just the push event`.
Then click on the `active` checkbox, and save with the `Add webhook` button.

**Comment by mkasberg** [comment]
@JohnRDOrazio The webhook should be set up!

**Comment by evang522** [comment]
I would actually suggest that it's worth it to go ahead and add this. Let me illustrate my use-case: my android phone is German locale. I've been working on helping to add German translations, but of course it takes time. Now, however, when the app loads, the incomplete German version is loading since it detects my phone's locale, and I can barely use the app on my phone anymore. 

Having the ability to switch at least to english would be really nice :)

**Comment by kas-catholic** [comment]
Thanks for the suggestion!

I'm doing a couple things that should make this situation better:

- I'll merge this PR. I think we're far enough along that we can let people select a language even if it's not perfect yet.
- I've added a `returnEmptyString: false` setting (in this PR) to configure i18next to fall back to English when translations are missing. (Weblate injects an empty string for missing translations so we need this.)

Can I make one request? Prioritizing the translation of these strings (German is the only language that's missing them) will make it clear how anyone else can contribute if they notice the missing strings: https://github.com/kas-catholic/confessit-web/blob/76d57321503e1f43551c08868cf6d139d609e781/public/locales/de/translation.json#L61-L62

**Pull request merged**
