### PR TITLE
Remove pt duplicate translation

### PR DESCRIPTION
**Pull request by kas-catholic**
We had duplicate translation files for pt and pt-BR. We're using pt-BR, so remove pt.

(See #71)

### CODE REVIEW

**Comment by kas-catholic** [comment]
@JohnRDOrazio I believe this is the best way to clean things up. Do we need to do anything on the Weblate side before or after I merge this?

**Comment by JohnRDOrazio** [comment]
Yes, I believe this should be done from weblate, since weblate all had it's own internal database with the translation information. I'm not sure what works happen if you just do it from here: would weblate recreate it again?
The sure way is to remove the translation from weblate. And that will be reflected in the next PR from weblate.

**Comment by JohnRDOrazio** [comment]
I suppose we can test to see what happens: go ahead and pull this, and we'll see how weblate responds. If it re-creates the `pt` translation, then we know that we just have to do it from weblate.

**Comment by JohnRDOrazio** [comment]
This actually seems to have worked, the `pt` translation is gone from weblate.

**Pull request merged**
