### PR TITLE
I18next action

### PR DESCRIPTION
**Pull request by JohnRDOrazio**
After many hours of testing, I finally came up with a solution that will work both from the command line, or from a Github workflow. I also took the opportunity to update to Node 20, if you think that's ok?

1) Need to install `chalk` explicitly among the dev-dependencies blocked at `v4` because `v5` changed to ES module syntax, but it seems that `i18next-scanner` doesn't have the right version as a dependency because it was pulling in `v5`, effectively breaking the scanner configuration
2) We previously had a little situation that was never quite fixed: if a new `<Trans>` component is placed in the code, when the scanner picked it up, it would use the default value (the text contents of the component) for both English and non English language files, which is not very desirable: you don't want to populate non English language files with English values. You only need the keys, but with empty values. I finally came up with a solution: use two separate configuration scripts, one that will update only the English language file and will populate keys related to `<Trans>` components with the default value; the other configuration script that will update all other non English language files and will populate keys related to `<Trans>` components with an empty value.
3) In order to automate this process I went ahead and created a Github workflow action that will trigger on push to `main` if any `.js` or `.jsx` files are changed.
4) I also set `sort` to true, so that keys will be sorted alphabetically. This will ensure that:
   * they are easy to navigate and find in the language files
   * they will all be in the same order in every language file

So far all is tested and working well, except maybe one little thing in the Github workflow action: it seems that a Husky hook is trying to run when the action tries to commit changes, but it can't find Husky. I don't know much about husky, how or where should it be installed inside the Github action?

### CODE REVIEW

**Comment by kas-catholic** [comment]
NodeJS 20.x sounds great, but I'd prefer to merge it in a separate commit/PR for numerous reasons. Would you like to make a separate PR for that? If not I'm happy to do it myself since you've done so much other work here, I could get it done quickly.

For i18next-scanner, I like your solution. Great idea to use separate configs! But I'm very hesitant about the auto-commit workflow. It's not that I don't think it will work, but that it's not the way I'm most comfortable working. I'd generally prefer, for a variety of reasons, to make the translations file changes in the same commit where the code changes. Fortunately, I actually think we can do this somewhat easily. [Husky](https://typicode.github.io/husky/) is a tool to automate the setup of git hooks that we're already using for a linting hook with Prettier. I think (hope) it would be easy to move your script out of the GitHub Action and instead run it as a hook when making a git commit, to include the translation changes as part of the same commit. I'd also be happy to work on doing this, using this PR as a starting point, or you can do the work yourself if you prefer. Let me know what you'd like me to help with.

**Comment by kas-catholic** [comment]
And of course, thanks for all your help with Translations! With that AI commit you did, we have very complete translations in several languages now!

**Comment by JohnRDOrazio** [comment]
> NodeJS 20.x sounds great, but I'd prefer to merge it in a separate commit/PR for numerous reasons.
Sure I can do that.
> I actually think we can do this somewhat easily. [Husky](https://typicode.github.io/husky/) is a tool to automate the setup of git hooks that we're already using for a linting hook with Prettier. I think (hope) it would be easy to move your script out of the GitHub Action and instead run it as a hook when making a git commit, to include the translation changes as part of the same commit.
I'm not familiar with Husky, though I'm interested in getting to know it. But best you take care of that. We could close this PR and I'll let you transport the `config` scripts in a new PR with a Husky hook pulling the sleigh 😄

**Comment by JohnRDOrazio** [comment]
Is it just a question of adding the `yarn dlx i18next-scanner` calls to the husky pre-commit file, perhaps just before `npx lint-staged `?
https://github.com/kas-catholic/confessit-web/blob/e26fc3fa91aafa9f61bcae652e4293bbf4e6ba8b/.husky/pre-commit#L4

**Comment by kas-catholic** [comment]
Yes, that should be it actually. Take a look at #86 and see if it seems good to you. (Or we can rebase and merge this PR if you prefer, I don't mind either way.)

**Pull request closed without merging**
